name = "imagix"
main = "src/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*", "/media/*"]

[vars]
WHATSAPP_NUMBER = "+917904140477"
ALLOWED_ORIGIN = "*"

# -----------------------------------------------------------------------------
# Dynamic Cloudflare KV & R2 Storage Bindings
# -----------------------------------------------------------------------------

[[kv_namespaces]]
binding = "IMAGIX_META"
id = "f4b97d9414cb4f6d9965b0cb5a1ba526"

[[r2_buckets]]
binding = "IMAGIX_PHOTOS"
bucket_name = "imagix-photography-images"
